### PR TITLE
Additon of All Contributors | Issue #11

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added all the contributors in readme.md file to give them appreciation.
Completed #11

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
please share screenshot.

**Comment by Shariq2003** [comment]
> please share screenshot.

image

**Comment by PranavBarthwal** [comment]
> > please share screenshot.
> 
> @PranavBarthwal sir, please check image

Whats ratna supermarket in first line? PLease fix

**Comment by Shariq2003** [comment]
> > > please share screenshot.
> > 
> > 
> > @PranavBarthwal sir, please check image
> 
> Whats ratna supermarket in first line? PLease fix

Oops let me correct

**Comment by Shariq2003** [comment]
> > > please share screenshot.
> > 
> > 
> > @PranavBarthwal sir, please check image
> 
> Whats ratna supermarket in first line? PLease fix

Check now sir

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
