### PR TITLE
Added the Dockerfile 

### LINKED ISSUE #19: Dockerize the Application
A Dockerfile simplifies deployment by packaging a full stack app, including all dependencies, into a consistent environment, ensuring smooth operation across different systems. It also streamlines testing, scaling, and collaboration, enabling easy setup and maintenance through containerization.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #19 
I have added the dockerfile to run the backend application.

commands to run :

cd templates
docker build -t backend-generator-cli .
docker run -p 3000:3000 backend-generator-cli

Screenshot 2024-10-08 203058

### CODE REVIEW

**Review by PranavBarthwal — CHANGES_REQUESTED** [review]
The docker file you have added is for the template of a backend project. You need the dockerize my entire application.

**Comment by haseebzaki-07** [comment]
@PranavBarthwal Please review my PR

**Comment by haseebzaki-07** [comment]
Hey @PranavBarthwal please review this

**Comment by haseebzaki-07** [comment]
hey @PranavBarthwal please review this PR

**Comment by haseebzaki-07** [comment]
@PranavBarthwal will you please review this PR

**Comment by haseebzaki-07** [comment]
@PranavBarthwal ???

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
